# These are supported funding model platforms

github: pentadex
patreon: pentadex
buy_me_a_coffee: pentadex
ko_fi: pentadex
open_collective: enterprise-osint-platform
community_bridge: enterprise-osint-platform
issuehunt: pentadex
liberapay: pentadex
tidelift: npm/enterprise-osint-platform
lfx_crowdfunding: enterprise-osint-platform
polar: pentadex
thanks_dev: pentadex
custom:
  - "https://www.paypal.me/pentadex"
  - "https://opencollective.com/enterprise-osint-platform"
  - "https://www.buymeacoffee.com/pentadex"
  - "https://github.com/sponsors/pentadex"
